### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jacimize** [ioos/registry#70]
Some of the IOOS links at http://catalog.ioos.us/services/filter/NAVY/DAP are broken or pointing to the wrong data.  Here are the corrections.  Data info URLS will present an HTML page with information about the file that can be used to request some of the data, or build a URL to use to get it.  Data Access URL’s will not return a valid result when accessed by a browser, but can be used as input to OpenDAP clients such as Integrated Data Viewer.  The two URL’s vary only by the addition of an ‘html’ extension to the data access URL to make the data info URL

For the record at http://catalog.ioos.us/services/531942228c0db3726c4c45b8 for RTOFS Surface:
The broken data Info URL is:
http://ecowatch.ncddc.noaa.gov/thredds/dodsC/onomads/rtofs/rtofs_surface_agg/best.html
but should be:
http://ecowatch.ncddc.noaa.gov/thredds/dodsC/rtofs/rtofs_surface_agg/CurvilinearOrthogonal_1684X1200-90p0N-120p0W/best.html
The data access URL should be:
http://ecowatch.ncddc.noaa.gov/thredds/dodsC/rtofs/rtofs_surface_agg/CurvilinearOrthogonal_1684X1200-90p0N-120p0W/best

For the record at: http://catalog.ioos.us/services/531943858c0db3726c4c45c7 For RTOFS volume:
The broken data info URL is:
http://ecowatch.ncddc.noaa.gov/thredds/dodsC/onomads/rtofs/rtofs_volume_agg/best.html
but should be:
http://ecowatch.ncddc.noaa.gov/thredds/dodsC/rtofs/rtofs_surface_agg/CurvilinearOrthogonal_1684X1200-90p0N-120p0W/best.html
The Data Access URL should be:
http://ecowatch.ncddc.noaa.gov/thredds/dodsC/rtofs/rtofs_surface_agg/CurvilinearOrthogonal_1684X1200-90p0N-120p0W/best

For the record at: http://catalog.ioos.us/services/5423020946a46b0e7600d0b7 For US East Nov 19,2009 to April 4, 2013:
The broken data info URL is:
http://ecowatch.ncddc.noaa.gov/thredds/dodsC/ncom_useast_agg_20091119_20130404/US_East_Nov_19,_2009_-_Apr_04_2013_best.ncd.html
but should be:
http://ecowatch.ncddc.noaa.gov/thredds/dodsC/ncom_useast_agg_20091119_20130404/US_East_Nov_19_2009_to_Apr_04_2013_best.ncd.html

The Data Access URL should be:
http://ecowatch.ncddc.noaa.gov/thredds/dodsC/ncom_useast_agg_20091119_20130404/US_East_Nov_19_2009_to_Apr_04_2013_best.ncd

The record at http://catalog.ioos.us/services/5423020946a46b0e7600d0b9 For Sendai Regional Forecast is referring to an old EDAC dataset that we no longer serve, it should be removed.

The record at http://catalog.ioos.us/services/5319408f8c0db3726c4c45a6 for Sendai Regional Forecast is mis-named, it is actually data for NAVO NCOM Relocatable model US East from February 2009 to November 18, 2009

The ‘American Seas’ records at http://catalog.ioos.us/services/5423020946a46b0e7600d0bb, http://catalog.ioos.us/services/5423020946a46b0e7600d0bd, 
http://catalog.ioos.us/services/5423020946a46b0e7600d0bf,
http://catalog.ioos.us/services/542ae34d46a46b0b7ce6944e
are erroneous extra records for AmSeas, which already has records for its current valid URLs; these records should be removed.

**Comment by robragsdale** [comment]
Thanks, @jacimize.  I'll update these URLs, accordingly.

**Comment by tlewis11** [comment]
Any progress on updating these links?  They are still reporting as broken.  Thank you.

**Comment by robragsdale** [comment]
These URLs have been updated in the registry and are being harvested by the [catalog](http://catalog.ioos.us/services/filter/NAVY/DAP) this morning.  The last two links submitted yesterday will not be picked up by the catalog until this weekend.  
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom/ncom_reg1_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom/ncom_reg2_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom/ncom_reg5_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom/ncom_reg6_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom/ncom_reg7_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom/ncom_reg10_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom/ncom_sfc8_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom_amseas_agg_20091119_20130404/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom_amseas_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom_us_east_before_depth_change_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom_useast_agg_20091119_20130404/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/ncom_us_east_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/hycom/hycom_reg1_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/hycom/hycom_reg6_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/hycom/hycom_reg7_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/hycom/hycom_reg17_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/hycom/hycom_sfc_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/rtofs/rtofs_surface_agg/catalog.xml
http://ecowatch.ncddc.noaa.gov/thredds/catalog/rtofs/rtofs_volume_agg/catalog.xml

I am closing this issue.  We can reopen if any new issues come up.

**Comment by scross015** [comment]
@robragsdale, thanks much!
