### ISSUE TITLE
Possible typo in SECOORA ISOWAFs 

### ISSUE THREAD

**Issue by ocefpaf** [ioos/registry#72]
[This ISOWAF endpoint](https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604653&componentId=&serviceType=ISOWAF&serviceStatus=&serviceUrl=platform&search=List+Collection+Sources) is missing an "s".  
`http://neptune.baruch.sc.edu/xenia/waf/usc/platform/` should be `http://neptune.baruch.sc.edu/xenia/waf/usc/platforms` instead.

(See: https://github.com/ioos/secoora/issues/150)

**Comment by rsignell-usgs** [comment]
@amilan17 do you have to fix this, or is it something that @robragsdale can fix also?

**Comment by amilan17** [comment]
fixed. Those records will be harvested by tomorrow.
Thanks for noticing!

Anna
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA/NESDIS/NCEI-Boulder
(formerly NGDC)

http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by robragsdale** [comment]
Issue fixed.
