### ISSUE TITLE
SOS MARACOOS WAF Cleanout

### ISSUE THREAD

**Issue by lukecampbell** [ioos/registry#73]
Hey Folks, 

Could I get a clean out for the MARACOOS WAF at 
http://sos.maracoos.org/maracoos-iso/

The WAF was regenerated today, a lot of the data have been moved and or renamed.

**Comment by amilan17** [comment]
yes - check back again tomorrow to ensure that all is as expected...

**Comment by lukecampbell** [comment]
@amilan17 Could you do a cleanout one more time? The last set of ISOs didn't have any of the OPeNDAP URLs, and I still can't identify how or why that happened so I ran NcISO from a remote machine to generate all the ISOs this time, and verified that the OPeNDAP URLs are there.

```xml
<srv:containsOperations>
  <srv:SV_OperationMetadata>
    <srv:operationName>
      <gco:CharacterString>OPeNDAP Client Access</gco:CharacterString>
    </srv:operationName>
    <srv:DCP gco:nilReason="unknown"/>
    <srv:connectPoint>
      <gmd:CI_OnlineResource>
        <gmd:linkage>
          <gmd:URL>
            http://sos.maracoos.org/stable/dodsC/hrecos/stationHRALBPH-agg.ncml
          </gmd:URL>
```

**Comment by amilan17** [comment]
Ok - I'll keep the configurations for clean out of MARACOOS until I have
confirmation from you that it is all good. Check back again tomorrow
(Thurs).


Anna
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
Metadata Specialist

NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center

http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by lukecampbell** [comment]
Thank you!

**Comment by brianmckenna** [comment]
@amilan17 looks like it has been cleared out successfully, can you remove the 'configurations for clean out'? We should be all set to with the records to be recreated.  Please let me know if we need to re-register each. Thank you!

**Comment by robragsdale** [comment]
@amilan17 The [production WAF](http://www.ngdc.noaa.gov/metadata/published/NOAA/IOOS/MARACOOS/iso_u/) is populated, the [test WAF](http://www.ngdc.noaa.gov/metadata/published/test/NOAA/IOOS/MARACOOS/iso_u/) is empty.  Does MARACOOS need to repopulated their WAF?  The catalog is showing 0 services and datasets right now and we need to resolve this as quickly as possible.  Thanks!

**Comment by amilan17** [comment]
looking into it right now.

Anna
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
Metadata Specialist

NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center

http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by amilan17** [comment]
So it seems that for some reason EMMA did not complete the processing of
MARACOOS last night/this morning. I re-ran processing and re-synced 440
records to production WAF (
http://www.ngdc.noaa.gov/metadata/published/NOAA/IOOS/MARACOOS/iso/) and
Geoportal.
I don't know what caused this issue, but I also turned off the cleanout
configurations of the previous run so *all* records won't disappear again,
but we should remember to be vigilant when we need to do another clean out
of records...

On a different, but most likely related note:

   1. This WAF is not registered with MARACOOS WAF in the IOOS Registry and,
   therefore, none of these records are getting harvested from this source.
      - http://sos.maracoos.org/maracoos-iso/
   2. This is the list of approved services or WAFs registered with
   MARACOOS:
      - *https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604646&search=List+Collection+Sources&serviceStatus=APPROVED&serviceType=&serviceUrl=&componentId=&max=20
      <https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604646&search=List+Collection+Sources&serviceStatus=APPROVED&serviceType=&serviceUrl=&componentId=&max=20>*


It looks like the sos maracoos WAF contains all the records (or more)
associated with the previously registered services. Are you trying to
replace these previous services with the metadata published in this WAF?



Anna
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
Metadata Specialist

NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center

http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by robragsdale** [comment]
@brianmckenna @lukecampbell The MARACOOS services are not being represented right now in the [Catalog](http://catalog.ioos.us/services/filter/MARACOOS/none).  @amilan17 is working on this.  

We need for you to clarify for us if you want to replace the [service URLs](https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604646&search=List+Collection+Sources&serviceStatus=APPROVED&serviceType=&serviceUrl=&componentId=&max=20) registered in the registry now with this new WAF URL http://sos.maracoos.org/maracoos-iso/? 

We will need to register this new WAF in the registry.  

Thanks.

**Comment by brianmckenna** [comment]
@robragsdale @amilan17 I'll be providing the list shortly for clarity. Quickly cleaning out a few dead links in there.

We will need to register that new WAF and keep the existing THREDDS service URLs, I will provide those links as well, so there's no confusion

**Comment by brianmckenna** [comment]
@amilan17 

Lets just go with the new WAF. Replaces the old entries. So...

URL | Point of Contact | Organization
------------- | ------------- | -------------
http://sos.maracoos.org/maracoos-iso/  | Brian McKenna - RPS ASA - bmckenna@asascience.com  | MARACOOS

Thanks for this.

**Comment by robragsdale** [comment]
@brianmckenna there are 22 records in the NGDC Geoportal now for MARACOOS.  It looks like these services are duplicated in the WAF.  @amilan17 Do we need to remove these records from Geoportal so we don't have duplication?

**Comment by brianmckenna** [comment]
@robragsdale correct, please remote those 22 existing records. thank you

**Comment by amilan17** [comment]
@brianmckenna 

Great! Thanks. 
This WAF is now submitted: 
https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604646&componentId=&serviceType=&serviceStatus=SUBMITTED&serviceUrl=&search=List+Collection+Sources
if all goes well we will see all of these metadata records in the test MARACOOS waf in EMMA 
http://www.ngdc.noaa.gov/metadata/published/test/NOAA/IOOS/MARACOOS/iso_u/

THEN, we will change the status to approved AND set the status of all these other services to 'for removal' 

https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604646&search=List+Collection+Sources&serviceStatus=APPROVED&serviceType=&serviceUrl=&componentId=&max=20

**Comment by robragsdale** [comment]
@brianmckenna has the contact information for the services in the WAF that are replacing the older services been updated and checked that information is not being lost/
