### ISSUE TITLE
MARACOOS UUID

### ISSUE THREAD

**Issue by robragsdale** [ioos/registry#74]
@amilan17 Is the MARACOOS UUID still {C664F631-6E53-4108-B8DD-EFADF558E408}?

**Comment by amilan17** [comment]
yes - it hasn't changed.

Anna
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
Metadata Specialist

NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center

http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by robragsdale** [comment]
MARACOOS UUID confirmed
