### ISSUE TITLE
Remove tds.ioos.us entries from Catalog

### ISSUE THREAD

**Issue by lukecampbell** [ioos/registry#77]
Hey Folks,

tds.ioos.us was shut down in favor of using GliderDAC (2.0) at data.ioos.us
Could you please remove all catalog entries from tds.ioos.us?

**Comment by robragsdale** [comment]
@amilan17 can you do a clean out of the GliderDAC WAF?  The status of the tds.ioos.us entries are set for removed in the registry.

**Comment by lukecampbell** [comment]
I've updated the GliderDAC WAF
http://data.ioos.us/gliders/metadata/

To ensure that it only contains valid GliderDAC 2 entries.

Thanks
