### ISSUE TITLE
Update of CeNCOOS metadata in registry

### ISSUE THREAD

**Issue by robragsdale** [ioos/registry#78]
Reference [Unharvestable CeNCOOS Services #395](https://github.com/ioos/catalog/issues/395#issuecomment-101715267) in catalog repository.  

@jpatterson should all of www.cencoos.rog dataset urls be removed from the [registry](https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604643&componentId=&serviceType=&serviceStatus=&serviceUrl=&search=List+Collection+Sources).

Should I, then update all URLs with "thredds.axiomalaska.com"  to "thredds.axiomdatascience.com" in the registry?

**Comment by susoson** [comment]
@robragsdale 
Yes all www.cencoos.org urls should be removed from the registry. 
Yes please update thredd.axiomalaska to thredds.axiomdatascience.

**Comment by susoson** [comment]
@robragsdale 
fyi - jpatterson is not me on GitHub!

**Comment by robragsdale** [comment]
@amilan17 can you set up a clean out of the CeNCOOS WAF for tonight?  I updated the status of the www.cencoos.org services to 'removed' in the registry.  I registered the new ISOWAF url thredds,axiomdatascience.com.  The older thredds,axiomalaska.com url was updated to 'for removal'.

**Comment by amilan17** [comment]
I changed the config - It should be cleaned out by tomorrow.

Anna
*~~~~~~Metadata Adds Meaning.~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center
http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by robragsdale** [comment]
Updated CeNCOOS services in registry.  Removed www.cencoos.org service urls.  Replaced axiomalaska.com with axiomdatascience.com in service url.  Clean out removed services not reporting in the catalog.  The list of services being harvested are listed [here](http://catalog.ioos.us/services/filter/CeNCOOS).
