### ISSUE TITLE
SOS MARACOOS WAF Cleanout

### ISSUE THREAD

**Issue by lukecampbell** [ioos/registry#79]
Could we get another WAF cleanout for MARACOOS?

**Comment by lukecampbell** [comment]
Geoportal is showing outdated ISOs which is causing IOOS Catalog to show mostly red for MARACOOS
Here's an example for the SLDMB 43416
http://www.ngdc.noaa.gov/geoportal/rest/document?id=%7B2A8A2AF7-1948-4543-9201-E3A063490E01%7D
Here's the actual ISO on our WAF
http://sos.maracoos.org/maracoos-iso/thredds_dodsC_sldmb_sldmb_43416_agg.ncml.xml

Is there anyway we could find out where that stale record is coming from?

**Comment by amilan17** [comment]
​The MARACOOS WAF is now set up for a cleanout. That old record should be
gone by tomorrow. ​

Anna
*~~~~~~Metadata Adds Meaning.~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center
http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by lukecampbell** [comment]
Ok thanks! I'll check catalog tomorrow and close the issue if there are no more issues.

**Comment by lukecampbell** [comment]
I'm still seeing issues
http://www.ngdc.noaa.gov/geoportal/rest/find/document?rid=local&ridName=NOAA%27s%20Geophysical%20Data%20Center&searchText=sys.siteuuid:%22{C664F631-6E53-4108-B8DD-EFADF558E408}%22&start=1&max=100&orderBy=relevance&maxSearchTimeMilliSec=10000&f=pjson

Search for "43416" and you'll notice that the metadata fields are stale compared with those on the WAF.

**Comment by lukecampbell** [comment]
This is what the WAF has:
```xml
<gmd:linkage>
    <gmd:URL>
        http://sos.maracoos.org/thredds/dodsC/sldmb/sldmb_43416_agg.ncml
    </gmd:URL>
</gmd:linkage>
```

http://sos.maracoos.org/maracoos-iso/thredds_dodsC_sldmb_sldmb_43416_agg.ncml.xml

But here's what shows up in geoportal

```xml
<gmd:linkage>
<gmd:URL>
http://localhost/stable/dodsC/sldmb/buoy43416-agg.ncml
</gmd:URL>
</gmd:linkage>
```

**Comment by amilan17** [comment]
I manually deleted all records from Geoportal and reharvested. I think it's
looking better now. However, please let me know as soon as this happens
again - 'full synchronization' may not be working as expected.

Anna
*~~~~~~Metadata Adds Meaning.~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center
http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by lukecampbell** [comment]
Looks good thanks,
