### ISSUE TITLE
MARACOOS WAF Cleanout

### ISSUE THREAD

**Issue by robragsdale** [ioos/registry#83]
@amilan17 Could you please set up a cleanout of the MARACOOS WAF?  Their are a number of old records that need to be removed.  Thanks.

**Comment by amilan17** [comment]
@robragsdale You should see these removed sometime tomorrow afternoon.

**Comment by robragsdale** [comment]
@brianmckenna The services were successfully harvested into the NCEI MARACOOS and showing up in the geoportal [harvesting diagram] (http://ioos.github.io/registry/ioos_registration_ngdc/).  They are not showing up in the IOOS catalog this morning.  MARACOOS is showing 0 datasets and services.    Can you or @lukecampbell do a manual harvest of the MARACOOS WAF so these show up in the catalog?

**Comment by lukecampbell** [comment]
Done:
http://catalog.ioos.us/services/filter/MARACOOS

**Comment by robragsdale** [comment]
IOOS Catalog harvesting services and services and datasets back in the Catalog
