### ISSUE TITLE
NDBC WAF Cleanout

### ISSUE THREAD

**Issue by robragsdale** [ioos/registry#89]
@amilan17 Could you please do a cleanout on the NDBC WAF? Thanks.

**Comment by amilan17** [comment]
​We should see the NDBC WAF cleaned out by tomorrow.​

Anna
*~~~~~~Metadata Adds Meaning~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
(formerly NOAA’s National Geophysical Data Center)
http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by robragsdale** [comment]
NDBC WAF clean out successful.

**Comment by robragsdale** [comment]
@amilan17 he ndbc cleanout removed the NDBC SOS service https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604649&componentId=&serviceType=&serviceStatus=&serviceUrl=&search=List+Collection+Sources that is stil approved.  It wasn't harvested into the WAF, @ocefpaf  Filipe was looking for the data.  See his issue #90.

**Comment by robragsdale** [comment]
NDBC data is showing up again in the [NDBC production WAF](http://www.ngdc.noaa.gov/metadata/published/NOAA/IOOS/NDBC/iso_u/) and in the [NGDC geoportal](http://www.ngdc.noaa.gov/geoportal/catalog/main/home.page).
